import dayjs from "dayjs";

export const initialState = {
  appGlobals: {
    urlConfig: {},
    isSidebarCollapsed: true,
    userMetaData: {
      user_name: "",
      user_id: "",
      profile_pic: "",
      permission: [],
      client_name: "lucknow",
      user_groups: [],
      client_logo: "",
      department: "",
    },
    configData: {},
    isSubmissionModalOpen: false,
    submissionModalData: {
      type: "",
      headerText: "",
      subText: "",
      key: "",
      body: {},
      requestType: "",
    },
    availableDepartments: {},
  },
  login: {
    username: "",
    password: "",
    aws_region: "",
    userPoolId: "",
    userPoolClientId: "",
    newPassword: "",
  },
  config: {
    isConfigLoading: false,
    isConfigBackdropLoading: false,
    config_entries: [],
    selectedClient: "Global",
    clientList: ["Global", "Lucknow"],
  },
  users: {
    isAllUsersListLoading: false,
    all_users: [],
    filters: {
      is_active: "",
      agency: "Lucknow",
    },
  },
  forms: {
    isEditing: false,
    isFormsBackdropLoading: false,
    isConfigModalOpen: false,
    isPinModalOpen: false,
    pinModalUserId: "",
    isUserModalOpen: false,
    isGroupModalOpen: false,
    configForm: {
      config_section: "",
      config_key: "",
      config_description: "",
      config_type: "",
      config_value: "",
    },
    userForm: {
      first_name: "",
      last_name: "",
      phone_number: "",
      email: "",
      badge_number: "",
      role: "",
      access: [],
      profile_picture_image: "",
      profile_picture: {},
    },
    groupForm: {
      group_name: "",
      role_desc: "",
      permissions: [],
    },
  },
  search: {
    tabMapper: {},
    expandedRecord: {
      isExpanded: false,
      isPoppedOut: false,
      detailSection: "",
      selectedPacket: "",
      caseId: "",
    },
    caseModal: {
      isCaseModalOpen: false,
      isQRModalOpen: false,
      isCaseEditView: true,
      isUploadModalOpen: false,
      selectedSection: "registration",
      errors: {
        case_details: [],
        messenger_details: [],
        packet_details: [],
        exhibit_details: [],
      },
      newCaseRecord: {
        case_details: {
          case_file_number: "",
          fir_number: "",
          general_diary_number: "",
          diary_date: dayjs().format("YYYY-MM-DD"),
          receipt_date: dayjs().format("YYYY-MM-DD"),
          entry_no: "",
          section: "",
          place_of_occurrence: "",
          police_station: "",
          court: "",
          district: "",
          state: "",
          registration_personnel_name: "",
          registration_personnel_designation: "",
          cug_number: "",
          cug_email: "",
          remarks: "",
          uploaded_files: {
            files: [],
            preview: [],
          },
        },
        messenger_details: {
          first_name: "",
          last_name: "",
          designation: "",
          identity: "",
          phone_number: "",
          email: "",
        },
        packet_details: {
          packet_type: "GENERAL",
          packet_number: "",
          number_of_exhibits: "",
          forwarding_authority_reference_date: dayjs().format("YYYY-MM-DD"),
          forwarding_authority_reference_number: "",
          forwarding_authority_name: "",
          forwarding_authority_address: "",
          seal_status: true,
          seal_details: "",
          is_seal_tailed: true,
          remarks: "",
          uploaded_files: {
            files: [],
            preview: [],
          },
        },
        exhibit_details: [],
      },
      responseCaseDetails: {},
    },
    transferModal: {
      isTransferModalOpen: false,
    },
    barcodeModal: {
      isBarcodeModalOpen: false,
      packetNumber: "",
    },
  },
  filters: {
    isFilterModalOpen: false,
    prevFilters: {},
    search: {
      case_file_number: "",
      exhibit_number: "",
      fir_number: "",
      section: "",
      exhibit_type: "",
      assigned_user_id: "",
      exclude_dispatched: false,
      exclude_rejected: false,
      // department_id: "",
      search_string: "",
      num_of_records: 1000000,
      page: 1,
    },
    packet_ledger: {
      page: 1,
      page_size: 50,
      case_file_number: "",
      packet_number: "",
      exhibit_number: "",
      status: "ACCEPTED",
      start_date: null,
      end_date: null,
      exclude_rejected: false,
    },
    exhibit_tracker: {
      case_file_number: "",
      exhibit_number: "",
      packet_number: "",
      exclude_rejected: false,
      fir_number: "",
      section: "",
      exhibit_type: "",
      assigned_user_id: "",
      department_id: 0,
      search_string: "",
      show_active_assignments: true,
      num_of_records: 1000000,
      page: 1,
    },
    transfers: {},
    all_documents: {
      page: 1,
      page_size: 50,
      case_file_number: "",
      packet_number: "",
      exhibit_number: "",
      assignment_number: "",
      start_date: null,
      end_date: null,
      department_id: 0,
    },
  },
  transfers: {
    isQRModalOpen: false,
    packet_number: "",
  },
  exhibitTracker: {
    isExhibitTrackerCardOpen: false,
    isIncomingPacketsModalOpen: false,
    exhibitId: "",
    exhibitData: "",
    isExhibitTrackerTransferModalOpen: false,
    transferringExhibits: [],
    isTransferModalOpen: false,
    noOfIncomingPackets: 0,
  },
  packetLedger: {
    expandedPacketLedger: {
      isExpanded: false,
      isPoppedOut: false,
      packetLedgerId: "",
    },
  },
  reportGen: {},
};
